--------------------------------------------------------
--  File created - Tuesday-August-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "JAIME"."CATEGORY" 
   (	"CATCODE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"NOSEATS" NUMBER, 
	"PRICE" NUMBER(*,0), 
	"SEATFROM" NUMBER, 
	"SEATTO" NUMBER, 
	"STATUS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JAIME.CATEGORY
SET DEFINE OFF;
Insert into JAIME.CATEGORY (CATCODE,DESCRIPTION,NOSEATS,PRICE,SEATFROM,SEATTO,STATUS) values ('2','TEST 1',100,50,1,100,null);
Insert into JAIME.CATEGORY (CATCODE,DESCRIPTION,NOSEATS,PRICE,SEATFROM,SEATTO,STATUS) values ('3','TEST 2',5,200,151,155,null);
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAIME"."CATEGORY_PK" ON "JAIME"."CATEGORY" ("CATCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."CATEGORY_TRG" 
BEFORE INSERT ON CATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."CATEGORY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORY_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."CATEGORY_TRG1" 
BEFORE INSERT ON CATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CATCODE IS NULL THEN
      SELECT CATEGORY_SEQ1.NEXTVAL INTO :NEW.CATCODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."CATEGORY_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "JAIME"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JAIME"."CATEGORY" MODIFY ("CATCODE" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."CATEGORY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."CATEGORY" MODIFY ("NOSEATS" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."CATEGORY" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."CATEGORY" MODIFY ("SEATFROM" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."CATEGORY" MODIFY ("SEATTO" NOT NULL ENABLE);
