--------------------------------------------------------
--  File created - Tuesday-August-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FIXTURE
--------------------------------------------------------

  CREATE TABLE "JAIME"."FIXTURE" 
   (	"MATCHID" NUMBER, 
	"MATCH_DATE" DATE, 
	"MATCHTIME" VARCHAR2(20 BYTE), 
	"MATCHAVAILABILITY" CHAR(1 BYTE), 
	"TEAMID1" NUMBER, 
	"TEAMID2" NUMBER, 
	"MATCHNAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JAIME.FIXTURE
SET DEFINE OFF;
Insert into JAIME.FIXTURE (MATCHID,MATCH_DATE,MATCHTIME,MATCHAVAILABILITY,TEAMID1,TEAMID2,MATCHNAME) values (1,to_date('08/20/2023','MM/DD/RRRR'),'7:11:20 pm',null,1,21,'WEEKEND GAME (BULACAN VS. PAMPANGA) PART 1');
--------------------------------------------------------
--  DDL for Index FIXTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAIME"."FIXTURE_PK" ON "JAIME"."FIXTURE" ("MATCHID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger FIXTURE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."FIXTURE_TRG" 
BEFORE INSERT ON FIXTURE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."FIXTURE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FIXTURE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."FIXTURE_TRG1" 
BEFORE INSERT ON FIXTURE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."FIXTURE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FIXTURE_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."FIXTURE_TRG2" 
BEFORE INSERT ON FIXTURE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."FIXTURE_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table FIXTURE
--------------------------------------------------------

  ALTER TABLE "JAIME"."FIXTURE" MODIFY ("TEAMID1" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."FIXTURE" MODIFY ("TEAMID2" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."FIXTURE" MODIFY ("MATCHID" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."FIXTURE" MODIFY ("MATCH_DATE" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."FIXTURE" MODIFY ("MATCHTIME" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."FIXTURE" MODIFY ("MATCHNAME" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."FIXTURE" ADD CONSTRAINT "FIXTURE_PK" PRIMARY KEY ("MATCHID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
