--------------------------------------------------------
--  File created - Tuesday-August-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALE
--------------------------------------------------------

  CREATE TABLE "JAIME"."SALE" 
   (	"SALEID" NUMBER, 
	"TICKETNUMBER" VARCHAR2(20 BYTE), 
	"NUM_SEATS" NUMBER, 
	"CATEGORYID" NUMBER(*,0), 
	"MATCHID" NUMBER, 
	"PRICE" NUMBER(*,0), 
	"SALES_DATE" DATE, 
	"SALES_TIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JAIME.SALE
SET DEFINE OFF;
Insert into JAIME.SALE (SALEID,TICKETNUMBER,NUM_SEATS,CATEGORYID,MATCHID,PRICE,SALES_DATE,SALES_TIME) values (3,'000001',3,2,1,50,to_date('08/15/2023','MM/DD/RRRR'),'12:51 am');
Insert into JAIME.SALE (SALEID,TICKETNUMBER,NUM_SEATS,CATEGORYID,MATCHID,PRICE,SALES_DATE,SALES_TIME) values (4,'000004',5,3,1,200,to_date('08/15/2023','MM/DD/RRRR'),'01:01 am');
--------------------------------------------------------
--  DDL for Index SALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAIME"."SALES_PK" ON "JAIME"."SALE" ("SALEID", "TICKETNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SALE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."SALE_TRG" 
BEFORE INSERT ON SALE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."SALE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."SALES_TRG" 
BEFORE INSERT ON SALE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."SALES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."SALE_TRG1" 
BEFORE INSERT ON SALE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."SALE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALE_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."SALE_TRG2" 
BEFORE INSERT ON SALE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SALEID IS NULL THEN
      SELECT SALE_SEQ2.NEXTVAL INTO :NEW.SALEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."SALE_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table SALE
--------------------------------------------------------

  ALTER TABLE "JAIME"."SALE" MODIFY ("SALEID" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SALE" MODIFY ("TICKETNUMBER" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SALE" MODIFY ("NUM_SEATS" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SALE" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SALE" MODIFY ("MATCHID" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SALE" ADD CONSTRAINT "SALES_PK" PRIMARY KEY ("SALEID", "TICKETNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JAIME"."SALE" MODIFY ("SALES_DATE" NOT NULL ENABLE);
