--------------------------------------------------------
--  File created - Tuesday-August-15-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SOCCERSYS_USERS
--------------------------------------------------------

  CREATE TABLE "JAIME"."SOCCERSYS_USERS" 
   (	"USERID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FULLNAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JAIME.SOCCERSYS_USERS
SET DEFINE OFF;
Insert into JAIME.SOCCERSYS_USERS (USERID,USERNAME,PASSWORD,FULLNAME) values (1,'admin','admin','Administrator');
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAIME"."USERS_PK" ON "JAIME"."SOCCERSYS_USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JAIME"."USERS_TRG" 
BEFORE INSERT ON "SOCCERSYS_USERS" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USERID IS NULL THEN
      SELECT USERS_SEQ.NEXTVAL INTO :NEW.USERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "JAIME"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table SOCCERSYS_USERS
--------------------------------------------------------

  ALTER TABLE "JAIME"."SOCCERSYS_USERS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SOCCERSYS_USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SOCCERSYS_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SOCCERSYS_USERS" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "JAIME"."SOCCERSYS_USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
